name: gather 2019 ncov

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  run:
    
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: install dependencies
      run: |
        cd 2019-ncov-crawler
        npm install
        
    - name: gather datas
      run: |
        cd 2019-ncov-crawler
        node index.js
      
    - name: Add & Commit
      uses: EndBug/add-and-commit@v2 # You can change this to use a specific version
      with: # See more info about inputs below
        author_name: uhziel
        author_email: uhziel@gmail.com
        cwd: "."
        message: "commit the datas of 2019 ncov"
        path: "."
        pattern: "*.json"
        force: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
