name: gather 2019 ncov

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  run:
    
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: install dependencies
      run: |
        cd 2019-ncov-crawler
        npm install
        
    - name: gather datas
      run: npm index.js
      
    - name: Add & Commit
      uses: EndBug/add-and-commit@v3.0.0
      with:
        # The name of the user that will be displayed as the author of the commit
        author_name: uhziel
        # The email of the user that will be displayed as the author of the commit
        author_email: uhziel@gmail.com
        # The message for the commit
        message: commit the datas of 2019-ncov-crawler
        # The pattern that mathces file names
        pattern: '*.json'
